# -*- coding: utf-8 -*-
"""Ramen rating.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tqJuNduIihr-JpM1E39Q3EI8Q5q7JjoM
"""


import pandas as pd #data processing
import matplotlib.pyplot as plt #data visualisation
import seaborn as sns #data visualisation

df = pd.read_csv('ramen-good.txt',sep=";")
df.head()

df.shape

df.isna().sum() #chercher the missing data

df=df.dropna(subset=['Style']) #drop the missing data

df["Style"].isna().sum()

df['Style'].unique()

print(len(df["Style"].unique()), 'Style')

df['Style'].value_counts()

df['Country'].unique()

print(len(df["Country"].unique()), 'Countries')

df['Country'].value_counts()

df['Brand'].unique()

print(len(df["Brand"].unique()), 'Brand')

top10=df.dropna()
print(top10)

top10 = top10[top10['Top Ten'] != ' '] #if the data in Top Ten column contains '\n' we can ignore it
top10 = top10.sort_values('Top Ten' ) #and we sort it by year
top10

df['Brand'].value_counts()[:10]

#First, let's see how many ramen brands are in our data
print(len(df['Brand'].unique()))

#Let's see if Stars column has invalid value.
for s in df['Stars']:
  try:
    s=float(s)
  except:
    print(s)

df=df[df['Stars'] !='Unrated']
print(df[df['Stars']=='Unrated']['Stars'].sum()) #make sure if there are no 'Unrated'

df['Brand']

brands = list(df['Brand'].unique())
counter = [0.0]*355


brands_cnt = dict(zip(brands, counter)) #create dictionary to count all ratings and then save the averages
#print(brands_cnt['Nissin'])

for brand in brands:
    brands_data = df[df['Brand'] == brand]
    for star in brands_data['Stars']:
        brands_cnt[brand] += float(star) #count all ratings
    brands_cnt[brand] /= len(brands_data) #average

print(brands_cnt)

top50ratings = [] #list for saving the brand name and its average rating
for key, values in brands_cnt.items():
    top50ratings.append([key,values])

#print the top 50 ramen ratings by brand
top50ratings = sorted(top50ratings, key = lambda x : x[1], reverse = True) #sorting values in descending order
output1=[]
output2=[]
output3=[]
for i in range(50):
    output2+=[top50ratings[i][0]]
    output3+=[round(top50ratings[i][1],2)]
d={'top50rating':output2,'top50ratinground':output3}
df_topratings = pd.DataFrame(d)
df_topratings.index += 1 
df_topratings.head()

#Data visualisation
#count Plot
sns.set(style = 'darkgrid')
f, ax = plt.subplots(1,1,figsize = (15,5))
sns.countplot(x = 'Country', data = df)
plt.xticks(rotation=90)

plt.show()

labels = 'Pack', 'Bowl', 'Cup' , 'Tray', 'Box' #We can't include 'Bar' and 'Can' because they only appear once in our data.
size = [1531, 481, 450, 108, 6]

f, ax = plt.subplots(1,1, figsize= (10,10))

ax.pie(size, labels = labels,autopct = '%1.2f%%', startangle = 180)
ax.axis('equal')
ax.set_title("Style", size = 20)

plt.show()